# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "naviteq-eks-app-dev-bucket"
    encrypt = true
    key     = "./terraform.tfstate"
    profile = "default"
    region  = "eu-central-1"
  }
}
