apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "weather-web-app.labels" . | nindent 4 }}
  name: {{ .Values.appName }}-svc
  namespace: {{ .Values.namespace }}   
spec:
  ports:
  - name: 5000-5000
    port: {{ int .Values.service.port | int }}
    protocol: TCP
    targetPort: {{ .Values.service.port | int }}
  selector:
    {{- include "weather-web-app.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
